//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onlineshopowner_api.Infrastructure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class branch
    {
        public int id { get; set; }
        public Nullable<int> location_id { get; set; }
        public Nullable<int> shop_id { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual Shop Shop { get; set; }
    }
}
