//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onlineshopowner_api.Infrastructure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class clientorder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public clientorder()
        {
            this.InternalTransactions = new HashSet<InternalTransaction>();
            this.OrderDetails = new HashSet<OrderDetail>();
            this.Payins = new HashSet<Payin>();
        }
    
        public int order_id { get; set; }
        public Nullable<int> client_id { get; set; }
        public Nullable<decimal> total_price { get; set; }
        public Nullable<System.DateTime> order_date { get; set; }
        public string order_status { get; set; }
        public Nullable<decimal> latitude { get; set; }
        public Nullable<decimal> longitude { get; set; }
        public Nullable<int> shopid { get; set; }
        public Nullable<int> delivery_id { get; set; }
        public string clientdeliveryPIN { get; set; }
        public Nullable<System.DateTime> clientrecievedata { get; set; }
        public Nullable<System.DateTime> deliveryshoprecievedata { get; set; }
        public string shopdeliveryPin { get; set; }
        public Nullable<decimal> deliverycost { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual DeliveryProvider DeliveryProvider { get; set; }
        public virtual Shop Shop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InternalTransaction> InternalTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payin> Payins { get; set; }
    }
}
