//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onlineshopowner_api.Infrastructure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryProvider
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DeliveryProvider()
        {
            this.DeliveryOrders = new HashSet<DeliveryOrder>();
            this.DeliveryWorkingHours = new HashSet<DeliveryWorkingHour>();
        }
    
        public int delivery_Id { get; set; }
        public string Provider_Type { get; set; }
        public string note_text { get; set; }
        public Nullable<bool> active_bit { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> update_at { get; set; }
    
        public virtual DeliveryAgent DeliveryAgent { get; set; }
        public virtual DeliveryAgent DeliveryAgent1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeliveryOrder> DeliveryOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeliveryWorkingHour> DeliveryWorkingHours { get; set; }
        public virtual PersonDelivery PersonDelivery { get; set; }
        public virtual regiondelivery regiondelivery { get; set; }
        public virtual regiondelivery regiondelivery1 { get; set; }
        public virtual regiondelivery regiondelivery2 { get; set; }
        public virtual ShopDelivery ShopDelivery { get; set; }
    }
}
