//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onlineshopowner_api.Infrastructure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryAgent
    {
        public int Delivery_Agent_Id { get; set; }
        public string name { get; set; }
        public string phone_number { get; set; }
        public string email { get; set; }
        public string logo_url { get; set; }
    
        public virtual DeliveryProvider DeliveryProvider { get; set; }
        public virtual DeliveryProvider DeliveryProvider1 { get; set; }
    }
}
