//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onlineshopowner_api.Infrastructure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deliver
    {
        public int deliver_id { get; set; }
        public Nullable<int> deliver_partner_agent_id { get; set; }
        public Nullable<int> deliver_partner_id { get; set; }
        public Nullable<int> person_id { get; set; }
        public Nullable<int> order_id { get; set; }
    
        public virtual clientorder clientorder { get; set; }
        public virtual DeliveryPartnerAgent DeliveryPartnerAgent { get; set; }
        public virtual DeliverPartnerperson DeliverPartnerperson { get; set; }
        public virtual Person Person { get; set; }
    }
}
