//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onlineshopowner_api.Infrastructure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryOrder
    {
        public int delivery_order_id { get; set; }
        public Nullable<int> order_id { get; set; }
        public Nullable<int> delivery_id { get; set; }
        public Nullable<System.DateTime> assigned_at { get; set; }
        public Nullable<System.DateTime> delivered_at { get; set; }
        public string delivery_status { get; set; }
        public Nullable<decimal> delivery_cost { get; set; }
    
        public virtual clientorder clientorder { get; set; }
        public virtual DeliveryProvider DeliveryProvider { get; set; }
    }
}
