//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onlineshopowner_api.Infrastructure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryWorkingHour
    {
        public int id { get; set; }
        public int delivery_id { get; set; }
        public string weekday { get; set; }
        public System.TimeSpan open_time { get; set; }
        public System.TimeSpan close_time { get; set; }
    
        public virtual DeliveryProvider DeliveryProvider { get; set; }
    }
}
