//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onlineshopowner_api.Infrastructure.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class online_shopEntities2 : DbContext
    {
        public online_shopEntities2()
            : base("name=online_shopEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admain> admains { get; set; }
        public virtual DbSet<branch> branches { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<clientorder> clientorders { get; set; }
        public virtual DbSet<DeliveryProvider> DeliveryProviders { get; set; }
        public virtual DbSet<DeliveryWorkingHour> DeliveryWorkingHours { get; set; }
        public virtual DbSet<InternalTransaction> InternalTransactions { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<Payin> Payins { get; set; }
        public virtual DbSet<Payout> Payouts { get; set; }
        public virtual DbSet<PendingRegistration> PendingRegistrations { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<regiondelivery> regiondeliveries { get; set; }
        public virtual DbSet<Region> Regions { get; set; }
        public virtual DbSet<Shop> Shops { get; set; }
        public virtual DbSet<ShopCategory> ShopCategories { get; set; }
        public virtual DbSet<ShopOwner> ShopOwners { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    
        public virtual ObjectResult<GetDelivery_Result> GetDelivery(Nullable<decimal> shoplatitude, Nullable<decimal> shoplongitude, Nullable<decimal> clientlatitude, Nullable<decimal> clientlongitude)
        {
            var shoplatitudeParameter = shoplatitude.HasValue ?
                new ObjectParameter("shoplatitude", shoplatitude) :
                new ObjectParameter("shoplatitude", typeof(decimal));
    
            var shoplongitudeParameter = shoplongitude.HasValue ?
                new ObjectParameter("shoplongitude", shoplongitude) :
                new ObjectParameter("shoplongitude", typeof(decimal));
    
            var clientlatitudeParameter = clientlatitude.HasValue ?
                new ObjectParameter("clientlatitude", clientlatitude) :
                new ObjectParameter("clientlatitude", typeof(decimal));
    
            var clientlongitudeParameter = clientlongitude.HasValue ?
                new ObjectParameter("clientlongitude", clientlongitude) :
                new ObjectParameter("clientlongitude", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDelivery_Result>("GetDelivery", shoplatitudeParameter, shoplongitudeParameter, clientlatitudeParameter, clientlongitudeParameter);
        }
    
        public virtual ObjectResult<getproduct_Result> getproduct(Nullable<int> shopid, Nullable<int> limit, Nullable<int> offset, string searchbyproductname, string searchbycategory, string searchbyshoptype)
        {
            var shopidParameter = shopid.HasValue ?
                new ObjectParameter("shopid", shopid) :
                new ObjectParameter("shopid", typeof(int));
    
            var limitParameter = limit.HasValue ?
                new ObjectParameter("limit", limit) :
                new ObjectParameter("limit", typeof(int));
    
            var offsetParameter = offset.HasValue ?
                new ObjectParameter("offset", offset) :
                new ObjectParameter("offset", typeof(int));
    
            var searchbyproductnameParameter = searchbyproductname != null ?
                new ObjectParameter("searchbyproductname", searchbyproductname) :
                new ObjectParameter("searchbyproductname", typeof(string));
    
            var searchbycategoryParameter = searchbycategory != null ?
                new ObjectParameter("searchbycategory", searchbycategory) :
                new ObjectParameter("searchbycategory", typeof(string));
    
            var searchbyshoptypeParameter = searchbyshoptype != null ?
                new ObjectParameter("searchbyshoptype", searchbyshoptype) :
                new ObjectParameter("searchbyshoptype", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getproduct_Result>("getproduct", shopidParameter, limitParameter, offsetParameter, searchbyproductnameParameter, searchbycategoryParameter, searchbyshoptypeParameter);
        }
    
        public virtual int insertorderafterpayment(Nullable<int> shopid, Nullable<decimal> totalpriceProduct, Nullable<decimal> deliverycost, Nullable<decimal> latitude, Nullable<decimal> longitude, Nullable<int> deliveryid, string paymentmethod, Nullable<int> clientId, ObjectParameter orderId)
        {
            var shopidParameter = shopid.HasValue ?
                new ObjectParameter("shopid", shopid) :
                new ObjectParameter("shopid", typeof(int));
    
            var totalpriceProductParameter = totalpriceProduct.HasValue ?
                new ObjectParameter("totalpriceProduct", totalpriceProduct) :
                new ObjectParameter("totalpriceProduct", typeof(decimal));
    
            var deliverycostParameter = deliverycost.HasValue ?
                new ObjectParameter("deliverycost", deliverycost) :
                new ObjectParameter("deliverycost", typeof(decimal));
    
            var latitudeParameter = latitude.HasValue ?
                new ObjectParameter("latitude", latitude) :
                new ObjectParameter("latitude", typeof(decimal));
    
            var longitudeParameter = longitude.HasValue ?
                new ObjectParameter("longitude", longitude) :
                new ObjectParameter("longitude", typeof(decimal));
    
            var deliveryidParameter = deliveryid.HasValue ?
                new ObjectParameter("deliveryid", deliveryid) :
                new ObjectParameter("deliveryid", typeof(int));
    
            var paymentmethodParameter = paymentmethod != null ?
                new ObjectParameter("paymentmethod", paymentmethod) :
                new ObjectParameter("paymentmethod", typeof(string));
    
            var clientIdParameter = clientId.HasValue ?
                new ObjectParameter("clientId", clientId) :
                new ObjectParameter("clientId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertorderafterpayment", shopidParameter, totalpriceProductParameter, deliverycostParameter, latitudeParameter, longitudeParameter, deliveryidParameter, paymentmethodParameter, clientIdParameter, orderId);
        }
    
        public virtual int Recieveorderfromdeliverytoclient(Nullable<int> orderid, Nullable<int> delievry_id, string clientdeliveryPin, ObjectParameter isexecute)
        {
            var orderidParameter = orderid.HasValue ?
                new ObjectParameter("orderid", orderid) :
                new ObjectParameter("orderid", typeof(int));
    
            var delievry_idParameter = delievry_id.HasValue ?
                new ObjectParameter("delievry_id", delievry_id) :
                new ObjectParameter("delievry_id", typeof(int));
    
            var clientdeliveryPinParameter = clientdeliveryPin != null ?
                new ObjectParameter("clientdeliveryPin", clientdeliveryPin) :
                new ObjectParameter("clientdeliveryPin", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Recieveorderfromdeliverytoclient", orderidParameter, delievry_idParameter, clientdeliveryPinParameter, isexecute);
        }
    
        public virtual int recieveorderfromshoptoorder(Nullable<int> orderid, Nullable<int> shopid, Nullable<int> delivery_id, string shopdeliverypin, ObjectParameter iscorrectdelivery)
        {
            var orderidParameter = orderid.HasValue ?
                new ObjectParameter("orderid", orderid) :
                new ObjectParameter("orderid", typeof(int));
    
            var shopidParameter = shopid.HasValue ?
                new ObjectParameter("shopid", shopid) :
                new ObjectParameter("shopid", typeof(int));
    
            var delivery_idParameter = delivery_id.HasValue ?
                new ObjectParameter("delivery_id", delivery_id) :
                new ObjectParameter("delivery_id", typeof(int));
    
            var shopdeliverypinParameter = shopdeliverypin != null ?
                new ObjectParameter("shopdeliverypin", shopdeliverypin) :
                new ObjectParameter("shopdeliverypin", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("recieveorderfromshoptoorder", orderidParameter, shopidParameter, delivery_idParameter, shopdeliverypinParameter, iscorrectdelivery);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    }
}
