//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onlineshopowner_api.Infrastructure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class regiondelivery
    {
        public int region_deliveryid { get; set; }
        public Nullable<int> delivery_id { get; set; }
        public Nullable<int> region_id { get; set; }
    
        public virtual DeliveryProvider DeliveryProvider { get; set; }
        public virtual DeliveryProvider DeliveryProvider1 { get; set; }
        public virtual DeliveryProvider DeliveryProvider2 { get; set; }
        public virtual Region Region { get; set; }
    }
}
